### ISSUE TITLE
[BUG] IOEventのRead系イベントでEOF判定ができない

### ISSUE THREAD

**Issue by public-jun** [public-jun/webserv#114]
## 内容
- ReadCGIでCGIからの書き込みの終了判定ができていない。

## 再現手順 && 出力

- 再現手順

- 出力 (エラー内容)

## 改善手段

- 検討がつくなら書く

**Comment by risudo** [comment]
これ、ReadFileも同じ状況ですよね。どうしたらいいんや…

**Comment by public-jun** [comment]
> これ、ReadFileも同じ状況ですよね。どうしたらいいんや…

read系のIOEventは全部同じなので自分がまるっと対応します👍
