### ISSUE TITLE
POSTメソッド時の作成されるファイル名について

### ISSUE THREAD

**Issue by risudo** [public-jun/webserv#139]
現状、POSTメソッド実行時にはタイムスタンプをファイル名にしていると思うのですが、これをリクエストターゲットをそのまま使用してもいいのではと思いました。

おそらく、タイムスタンプにしているのは、ファイル名が競合しないようにということだと思うのですが、もしターゲットのファイルがサーバー上に既に存在していたら[409](https://developer.mozilla.org/ja/docs/Web/HTTP/Status/409)を返すという実装でもいいのかなと思いました。

2人の意見を聞きたいです！

**Comment by teamaru** [comment]
> 現状、POSTメソッド実行時にはタイムスタンプをファイル名にしていると思うのですが、これをリクエストターゲットをそのまま使用してもいいのではと思いました。

リクエストターゲットをそのまま使用 = ユーザーのファイル名を使うってことでいいのかな？

ファイル名競合の回避もそうだけど、脆弱性の観点でファイル名生成してました。
以下の「脆弱性対策」の欄がちょっと詳しいです。
https://otomizu.work/2019/05/22/php-fileupload/#toc_id_3

あとファイルアップロード時に、
- ユーザーがサーバー内のファイル名事情を考える必要がある
- サーバーのファイル管理がユーザーのファイル名に左右される

という点で、サーバー内管理のためにはファイル名生成が無難な気もします。

今の仕事だと、サーバー内でのファイル管理は生成したファイル名を使用して、
ユーザーにファイルを表示させるときはDB内に保存したオリジナルのファイル名を使ってます。

**Comment by public-jun** [comment]
提案ありがとうございます！

>おそらく、タイムスタンプにしているのは、ファイル名が競合しないようにということだと思うのですが、もしターゲットのファイルがサーバー上に既に存在していたら[409](https://developer.mozilla.org/ja/docs/Web/HTTP/Status/409)を返すという実装でもいいのかなと思いました。

今回のuploadパスが指定されているという課題要件からすると、ターゲットはあくまでもファイルをアップロードするためのインターフェイスという認識です。
なので仮に同名であっても別々のファイルという扱いでいいのかなと思いました。

**Comment by risudo** [comment]
2人ともありがとうございます！

脆弱性の観点は考えていなかったので納得しました！
ユーザーが作成したファイル名が分からないと不都合なのでは、と思ったのですが、実際のファイル名とユーザーが扱うファイル名が一致しなくても大丈夫という点も納得しました！
