### ISSUE TITLE
[BUG]auto indexで表示されるファイル・ディレクトリのクリック時に404

### ISSUE THREAD

**Issue by teamaru** [public-jun/webserv#140]
## 内容
- auto indexで表示されるファイル・ディレクトリのクリック時に404

## 再現手順 && 出力
- 下記設定で```http://localhost:4242/auto_index/```へアクセス
```
server {
  listen 127.0.0.1:4242;
  server_name webserv;
  max_client_body_size 1m;

  root ./docs;
  allowed_method GET POST DELETE;

  location /auto_index/ {
    alias ./docs/;
    auto_index on;
  }
```
- 表示されるファイル・ディレクトリをクリック
- 404エラーページが表示される
<img width="601" alt="1" src="https://user-images.githubusercontent.com/61214244/177043113-8c40adef-3396-4b45-b03f-f730ab8434bf.png">
<img width="1263" alt="2" src="https://user-images.githubusercontent.com/61214244/177043134-ffd76348-24f3-4b89-a9a1-7f372fdcda01.png">

## 期待する出力
- ファイルの表示もしくはディレクトリの遷移

## 改善手段
- 遷移先のURLが```/docs/index.html```や```/docs/allowed_method/```になっていて、パスが不適切かもです。
- ```/auto_index/allowed_method/```なら正しく表示されるので、リクエストのURLをベースに遷移すると良いかも
<img width="639" alt="名称未設定2" src="https://user-images.githubusercontent.com/61214244/177043143-4932546f-80ba-4074-9f06-592245d4b8db.png">

**Comment by risudo** [comment]
報告ありがとうございます！
直します！
